### ISSUE TITLE
dune pinned to 2.4 version in the image.

### ISSUE THREAD

**Issue by picojulien** [coq-community/docker-coq#6] opened 2020-05-26 13:57 UTC
I'm playing with the new dune feature that allows to use dune to compile coq project, and for this  
I need to use a version of dune >= 2.5 
However, in the current docker image dune is pined to version 2.4 in opam. Is there a specific reason for that ?

**Comment by erikmd** [comment] 2020-05-26 14:15
@picojulien thanks for the question, there is no specific reason to prefer the version 2.4, actually dune is pinned since this commit: https://github.com/coq-community/docker-base/commit/8aeecac886180dad13cff70e1ede551643e9bcb8 and the upside of pinning dune is twofold:
- as per https://github.com/coq-community/docker-base/issues/7 it reduce the build time as dune is pre-installed in the image
- the provided version is documented [in the Dockerfile](https://github.com/coq-community/docker-base/blob/8aeecac886180dad13cff70e1ede551643e9bcb8/Dockerfile#L65)

but the downside is, obviously, that we need to continuously check this version and bump it.

BTW the plan is precisely to rebuild all coqorg/coq and mathcomp/mathcomp images in this week (to benefit from Debian upstream updates as well)
So we should probably bump the `dune` version to `2.5.1` beforehand.
feel free to react if you see another change to perform meanwhile!

**Comment by picojulien** [comment] 2020-05-26 20:12
Good news, and many thanks for the explanation !

**Comment by erikmd** [comment] 2020-05-27 20:08
Closing as a duplicate of https://github.com/coq-community/docker-base/issues/8

**Closed by erikmd** 2020-05-27 20:08 UTC
Labels: duplicate
