### ISSUE TITLE
Please rebuild images with latest dune

### ISSUE THREAD

**Issue by JasonGross** [coq-community/docker-coq#55] opened 2023-04-06 11:38 UTC
I'm seeing opam decide to recompile Coq due to "upstream or system changes" in dune, if I try to install any Coq package https://github.com/coq-community/run-coq-bug-minimizer/actions/runs/4625517245/jobs/8181344979#step:5:457

**Comment by Alizter** [comment] 2023-04-06 11:41
@JasonGross You can also pin the Dune version to avoid the upgrade.

**Comment by Alizter** [comment] 2023-04-06 18:04
@JasonGross Once you pin you will have to upgrade once. What version are you current at that you want to stay at? You should pin to that. All pinning will do is tell the opam solver to not update that dependency once the version constraint is satisfied.

**Comment by Alizter** [comment] 2023-04-06 18:07
However if I have understood correctly you are saying that Dune is `3.6.1` and even when pinned to that verison, installing equations will cause a rebuild?

**Comment by JasonGross** [comment] 2023-04-06 18:20
> What version are you current at that you want to stay at?

3.6.1, according to `opam list`, and it's already pinned. Pinning does not prevent recompilation



https://github.com/coq-community/run-coq-bug-minimizer/actions/runs/4629119643/jobs/8188996268#step:5:518
https://github.com/coq-community/run-coq-bug-minimizer/actions/runs/4629119643/jobs/8188996268#step:5:556

> However if I have understood correctly you are saying that Dune is `3.6.1` and even when pinned to that verison, installing equations will cause a rebuild?

Yes

**Comment by Alizter** [comment] 2023-04-06 19:38
I have no idea what has happened there. I guess @erikmd you should update to 3.7.1 so that the version is stable.

**Comment by erikmd** [comment] 2023-04-06 22:09
Hi all!

Thanks for opening the issue 🙃

This is a normal issue, caused by the merge of https://github.com/ocaml/opam-repository/pull/23574 yesterday.

Feel free to let me know by an issue or by a Zulip message if you face with similar "upstream or system changes" anew.

For this symptom, the standard solution is to rebuild all images to incorporate the latest version of the package from upstream opam-repository. 

But as pointed out by @Alizter, we can now benefit from the dune.3.7.1 package, released 2 days ago.

I pushed a commit, a [docker-base](https://gitlab.com/coq-community/docker-base/-/pipelines/830634179) pipeline is on-going, and tomorrow I'll rebuild the docker-coq images.

**Comment by erikmd** [comment] 2023-04-06 22:12
BTW

> You can also pin the Dune version to avoid the upgrade.

dune is already pinned, cf. [this line](https://github.com/coq-community/docker-base/blob/794946bb6db9983a60b6f16c7e8a0c6660294596/base/single/Dockerfile#L93)

As said before, the only "issue" here is an upstream change in opam-repository.

Whatever is the pinning state of the dune package, every ocaml user in the ecosystem will need to update one's switch.

**Comment by erikmd** [comment] 2023-04-07 16:05
> and tomorrow I'll rebuild the docker-coq images.

A very last rebuild is on-going. Closing the issue now.

**Closed by erikmd** 2023-04-07 16:05 UTC

**Comment by Alizter** [comment] 2023-04-07 16:23
@erikmd Do you build the images on Gitlab? It should be possible to build them in Github.

**Comment by erikmd** [comment] 2023-04-09 09:06
@Alizter basically, all `{coqorg/base, coqorg/coq, mathcomp/mathcomp, mathcomp/mathcomp-dev}` Docker images are built within GitLab CI with the [docker-keeper](https://gitlab.com/erikmd/docker-keeper) tooling I developed (cf. my [Coq Workshop 2020 talk](https://coq-workshop.gitlab.io/2020/slides/Coq2020_02-02-docker-slides.pdf)), which is much more expressive w.r.t. what we can do with GHA (e.g., GHA workflows cannot use YAML `&anchors`), so no need to move away from this technical solution.

The only issue is that MathComp is not under an OSI-approved free license, and as a result, we don't benefit from CI minutes enough since a couple of months.

So I recently worked together with @Zimmi48 and @maximedenes:
* to implement [coq/bot#234](https://github.com/coq/bot/issues/234),
* generalize coqbot to change the gitlab domain name,
* and finally migrate the GitLab CI mathcomp repos to gitlab.inria.fr, which comes with Inria builtin runners.

As soon as all this is implemented, I'll post an announcement on Zulip.
